nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - /var/log/nginx/:/var/log/nginx/
    - /usr/local/nginx/conf:/usr/local/nginx-1.10.2/conf
    - /data/www/www:/home/www
  #links:
  #  - php53
  #  - php54
  #  - php56
  #  - mysql
  #  - memcache
